### ISSUE TITLE
Unable to add query parameters using .withRequestOptions()

### ISSUE THREAD

**Issue by nilsnh** [basti1302/traverson-angular#19] opened 2015-12-14 12:06 UTC
Hi there,

I'm using traverson-angular 2.1.0, with json-hal and angulars http service through `.useAngularHttp()`. Now I see that `.withTemplateParameters()` works but I'm running into an issue when I try to use `.withRequestOptions()` ([as suggested here](https://github.com/basti1302/traverson/issues/39#issuecomment-87198158)).

The problem: I do not see any query parameters added to the outgoing requests when using `.withRequestOptions()`.

Example of how I'm using the library:

````javascript
traverson.registerMediaType(TraversonJsonHalAdapter.mediaType, TraversonJsonHalAdapter);
var api = traverson.from(restService.serverUrl).jsonHal();
api.useAngularHttp();

api
  .follow('users', 'search', 'findByUserGroup')
  .withRequestOptions({
	qs: { 
		userGroup: userGroupName,
		projection: 'withUserComments'
	}
  })
  .getResource()
  .result
  .then(function (data) {
  	if (data._embedded) {
          callback(data._embedded);
  	}
    else {
     $log.debug("No users were found");
    }
  }, that.errorHandler);

````

Thanks in advance for any pointers on what could be the issue here.

**Comment by basti1302** [comment] 2015-12-21 13:06
Hi @nilsnh 

I can not reproduce the problem on my side. I used your example, including json-hal and Angular $http and I can see (in the network tab in dev tools) that there are query parameters on the requests.

To debug your issue I would include the non minified traverson-angular lib (traverson-angular.js instead of traverson-angular.min.js) and set a breakpoint in the mapOptions/mapQuery functions.

That's how mapQuery looks like, you should be able to find it in the source panel in traverson-angular.js:

```
    function mapQuery(mappedOptions, options) {                                                                                                               
      // options.qs would be correct since we are using request/request options  
      // object API, but a previous version of traverson-angular incorrectly        
      // used options.query instead, so we allow this also, to not break            
      // backwards compatibility.                                                   
      var qs =  options.qs || options.query;                                        
      if (qs) {                                                                     
        mappedOptions.params = qs;                                                  
      }                                                                             
    } 
```

Hope that helps.

Feel free to add more comments if you need more help!

I'm closing this for now, you are welcome to reopen it if you still think it is an issue with traverson-angular.

**Closed by basti1302** 2015-12-21 13:06 UTC
